# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 17
      
    #- name: Setup Android SDK
    #  uses: android-actions/setup-android@v2.0.10
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: sudotest
      run: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk unzip wget
    - name: Download and Install Android Command Line Tools
      run: |
            mkdir -p $HOME/android-sdk/cmdline-tools
            cd $HOME/android-sdk
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
            unzip cmdline-tools.zip -d cmdline-tools
            mv cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
            rm cmdline-tools.zip
    - name: Set up Environment Variables
      run: |
            echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
            echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
      

    - name: Accept Android SDK Licenses
      run: |
            yes | sdkmanager --licenses

    - name: Verify Installation
      run: sdkmanager --list


#    - name: Install dependencies
#      run: |
#          make install
    - name: Test ADB
      run: |
          make adb_test
          make run_emulator
    - name: Lint with pylint
      run: |
          #make lint
    - name: Test with pytest
      run: |
          make test
    - name: Format code
      run: |
          #make format
